/**
 * Реестр иконок Lucide, используемых на сайте.
 * Импортируйте только отсюда — вместе с optimizePackageImports в next.config
 * это гарантирует tree-shaking (в бандл попадают только нужные SVG).
 */
export type { LucideIcon } from "lucide-react";

export {
  Activity,
  ArrowRight,
  ArrowUpRight,
  Award,
  Baby,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  Crown,
  Dumbbell,
  HeartHandshake,
  Layers,
  Lightbulb,
  Loader2,
  Mail,
  Medal,
  MapPin,
  Menu,
  MessageCircle,
  Navigation,
  Package,
  ParkingCircle,
  Phone,
  Route,
  Send,
  Shield,
  ShoppingBag,
  ShowerHead,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Table2,
  Target,
  Trees,
  UserRound,
  Users,
  Wind,
  X,
  ZoomIn,
  Music,
  Flower2,
  Armchair,
  Volume2,
  VolumeX,
} from "lucide-react";
